# Generated by Django 3.1.2 on 2020-10-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201017_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteBookProduct',
            new_name='NoteBook',
        ),
    ]
